### ISSUE TITLE
Text appears out of text box and is cut off

### ISSUE THREAD

**Issue by joehrlein** [otfried/ipe#105]
Hi,

in ipe everything is fine but I have some issues looking at the pdfs with a pdf viewer (tested with several viewers):
Writing some text in a text box it sometimes happens that some parts of the text are outside the box. In some cases (I cannot reproduce right now) some top and bottom pixels sticking out of the box are cut off. I assume it's the same problem which occurs using line numbers in a lstlisting-environment (which I could reproduce and attach). In a pdf viewer there is an empty circle where in ipe (and the following png-export) the line number is placed as desired.
[minExample.zip](https://github.com/otfried/ipe-issues/files/541410/minExample.zip) (sorry for the zip-file; when uploading a (to me: regular) pdf-file github suggests to try another file type instead, e.g. pdf)
![minexample](https://cloud.githubusercontent.com/assets/16101646/19555941/20fb0276-96bf-11e6-8956-71d4783a7e04.png) (png-export of the output (problem does not occur in png-export))

Thank you for your help!
Kind regards,
Johannes

**Comment by otfried** [comment]
Well, this is tricky.   The `listings` style deliberately draws text outside the Latex bounding box.  Since pdflatex relies on this bounding box for clipping the form, the number disappears.

There is no automatic solution for this - Ipe has no other way to obtain bounding box information - so you have to manually add padding to text objects on the left.   You can do that by adding this style sheet to your document:

```
<ipestyle name="pad">
<textpad left="20" right="0" top="1" bottom="1"/>
</ipestyle>
```

**Comment by joehrlein** [comment]
Thank you for that workaround! It did the trick.
