### ISSUE TITLE
Stroke and fill opacity

### ISSUE THREAD

**Issue by make-github-pseudonymous-again** [otfried/ipe#134]
Allow different opacities for stroke and fill.

**Comment by otfried** [comment]
It turns out this is not as useful as I thought it would be:   As it's currently implemented, objects with both stroke and fill that are not opaque are rendered in a surprising way:   They are first filled, and then stroked.  Since the stroke typically overlays the filled area, the overlap is drawn twice, and looks different from the part of the stroke that is not also filled.

This means that in most situations, you may not want to use both stroke and fill when the object is not opaque, and so having distinct opacities for stroke and fill doesn't seem so useful now.    

Am I missing something?

**Comment by Willem3141** [comment]
If I may chime in here: I would sometimes like to use an object with a non-transparent stroke (opacity 100%) and a transparent fill. So for me, that at least would be a useful option (at the moment I have to duplicate the shape for this).

An more powerful alternative would be to have support for transparency groups, like for example TikZ has. The idea is that if you set opacity on a group, then the entire group at once is made transparent, without the artifacts caused by overlapping shapes.

**Comment by otfried** [comment]
After a bit of experimentation, it turns out that the PDF path drawing operators actually handle distinct opacities well:  drawing a filled and stroked shape with different opacities will not result in a funny overlap (but currently you will see one on the Ipe screen - I need to see if Cairo has a way of avoiding this).   Objects with opaque stroke and transparent fill work fine in both.

Transparency groups have been on my todo list for a long time, but they require rewriting the PDF generator significantly (in PDF, transparency groups must be represented by separate XForm objects, they cannot be embedded in the page stream).

**Comment by otfried** [comment]
Implemented in 7.2.12.
