### ISSUE TITLE
Bug in parsing <gridsize/> attribute

### ISSUE THREAD

**Issue by horasio** [otfried/ipe#141]
Hi Otfried,

The following does not parse (Parsing error when opening the file):

<gridsize name="1 mm" value="2.847"/>

It seems to have to do with the parsing of decimal/integer numbers because:
value="2.0" is accepted but value="2.1" is not.
(debian stable, ipe 7.2.7 compiled locally with liblua5.3)

Maybe it's a recent feature, not a bug, but I used to have decimal grid sizes... and it used to work.
If it's a deliberate change, then OK, I think can live with it ;-)
Best regards,
Sam

**Comment by horasio** [comment]
I see that a related bug was closed from 7.2.6 to 7.2.7.
My best guess is that previously fractional grid sizes were just silently rounded ?
Then I'll just round it in my ipe file as well.
Feels (just a little bit) awkward to not be able to have precise 1mm/1cm grids.
Sam

**Comment by otfried** [comment]
Ipe has not allowed fractional grid sizes since 7.0.0 - they were accepted in the style sheet, but silently rounded.  

Ipe 6 had fractional grid sizes, but there were issues with rounding errors.

If you want mm- correct drawings, I suggest you draw them as if 3 pts equal 1 mm.  Then, when you need the image, you scale it (for instance when including in Latex using \includegraphics) by the factor 1.05833333.

At some point I want to allow coordinates in Ipe files to be mm-correct, with the conversion to PDF points happening automatically when saving in PDF.
