### ISSUE TITLE
Scroll wheel panning

### ISSUE THREAD

**Issue by alfazaz** [otfried/ipe#158]
Hello,

Here is a pull request (that I can't post in the "Pull request" part).

Is it possible to change the scroll wheel of mouse (or two fingers move on touchpad which is the same on Linux) to panning ? That would be more natural and useful than zooming (and we could pan in every directions with nowadays wheels and touchpads).

I didn't find how to toggle this in configuration (but I can have misread docs ?).

Thanks
Alfazaz (coming from the very old xfig...)

**Comment by otfried** [comment]
A "pull request" means that you have already written the code, and I just have to merge it into my codebase.  Is that what you mean?

On my Linux system, two-finger touchpad events are delivered to Ipe as scrollwheel events (in particular, the position on the touchpad seems to be lost).  

All scrollwheel events (both from the touchpad and from the wheel on your mouse) are then handled by the function `MODEL:wheel_zoom` in `actions.lua`.   You can modify this function to do something different, in particular, you can try to change the panning instead of the zooming.   

Please share any solutions you find - this is an item on my todo list, especially on OSX.

On Windows 10, two-finger events on a touch screen already pan (and the two-finger zoom gesture zooms).

**Comment by alfazaz** [comment]
Sorry, I have no code ; I missunderstood the meaning of "pull request".

But, thanks for your informations. I will take a look for a solution now and, if I find it, I will give it to you.

**Comment by alfazaz** [comment]
Hello !

I tried to change function MODEL:wheel_zoom but it gets only a "distance" information and no direction so I can't pan in 2D.

On linux, the touchpad gives these events as vertical and horizontal panning (got with xev) :
ButtonPress and ButtonRelease for button 4   (to the up)
ButtonPress and ButtonRelease for button 5   (to the down)
ButtonPress and ButtonRelease for button 6   (to the left)
ButtonPress and ButtonRelease for button 7   (to the right)

Do you know how to map these events to panning in Ipe ?

**Comment by otfried** [comment]
I've implemented the feature now for Linux - you can get a snapshot here:

https://www.dropbox.com/s/4u4qtkcwwhtpatl/ipe-7.2.8-src.tar.gz?dl=0

It will be in the 7.2.8 release.

**Comment by alfazaz** [comment]
Ouaouh, thanks !!! I will give it a try as soon as possible ! :-)

Edit : well, I tried it and it works exactly as I wanted. Great !!!! I don't know when the 7.2.8 release will be out but it's a good evolution for it.
