### ISSUE TITLE
Short-Cuts not working

### ISSUE THREAD

**Issue by TillBerlin** [otfried/ipe#159]
I noticed that the short cut ctrl+E for editing a paragraph is not working under Windows.

Also when I draw  polyline it used to be the case that I could use very conveniently the short cut delete to get rid of the last point that I added. That was super helpful. Why did it disappear?

**Comment by otfried** [comment]
Ctrl+E for editing text objects works fine for me (Ipe 7.2.7 on Windows 10).    If it doesn't work for you, please provide more details when this happens - what exactly are you doing, starting from a fresh start of Ipe.   Did you change any of the key assignments?

The delete key indeed doesn't work anymore.   I will need to investigate - it turns out the delete key is not actually delivered to the tool.   This bug has probably been in Ipe for quite a while - since I'm not a Windows user, I wouldn't notice until somebody files a report - so thank you.

For the moment, you can put this line in your customization:
```
prefs.delete_key = "\8"
```
and use the Backspace key to delete the last vertex. (For some reason, Backspace gets to the tool, but Delete doesn't.)

**Comment by TillBerlin** [comment]
Thanks for the answer.
I remember that the error with ctrl+E happened, but I failed to reproduce it.
When it happens again, I will write here again.

What exactly is meant with adding the line to my customization? 
I added it to Tillstyle.isy, which I added then as a style file. But this lead to an error:

Cannot load stylesheet
Parsing error at 828

**Comment by otfried** [comment]
It turns out the Delete key is not delivered to Ipe at all - it generates no WM_CHAR message because it's an "extended key".
See https://www.gamedev.net/forums/topic/597049-c-wm-char-and-the-delete-key/ for the solution.

**Comment by otfried** [comment]
Fixed in 7.2.8.
