### ISSUE TITLE
Ipe crashes on empty paths (which are created by svgtoipe)

### ISSUE THREAD

**Issue by tinloaf** [otfried/ipe#163]
Hi,

current ipe cannot load a file containing this path:

```
<path>
0 0 m
</path>

```

However, a path like this is sometimes being created by svgtoipe, for example when converting the attached file (which I had to zip so that github allows me to attach it…)

I'm not sure if this is a bug in ipe or svgtoipe, but I think from http://ipe.otfried.org/manual/manual_47.html paths with "just a move" are not explicitly forbidden, right?

Regards,

Lukas

[crash.zip](https://github.com/otfried/ipe-issues/files/1368266/crash.zip)

**Comment by otfried** [comment]
What should Ipe do with such a path?   There is actually no way to represent such an object in Ipe now, so rejecting it seems the right thing to do to me.   As far as I can see,  the svg file has no visible contents either.

**Comment by tinloaf** [comment]
Yes, but I think refusing to open the file is probably not the correct behaviour? At least for SVGs, such an "useless" path is allowed by the specs, I think. For ipe, I also think that the manual does not forbid this. Thus, either ipe currently refuses to open a well-formed Ipe-XML file, or svgtoipe transforms a valid SVG file into an invalid Ipe XML file.

 Maybe it would be better to just silently ignore such paths? Either during conversion from SVG to Ipe-XML or when opening the file in ipe.

**Edit**: I looked at the code of both ipe and ipetosvg and could not figure out a "trivial" way of ignoring such things. For ipe, the problem is that for the file to open, `Path::create()` needs to return *something* (that is not NULL), and I'm not sure what. For svgtoipe, the problem is that `parse_path()` writes the commands to `out` as soon as it sees them. It would need to check if the path is "non-trivial" before writing anything.

**Comment by otfried** [comment]
It's always debatable what to do with ill-formed input.  One strategy is to accept as input nearly anything that can be interpreted in some way, but to conform strictly to the specs when writing output.

HTML browsers are extreme in this respect, since there is so much ill-formed HTML around.  SVG viewers again will try to interpret as much as they can, because there are so many different SVG-producers around.

There are not many Ipe-format producers around, and I think being strict on what Ipe accepts helps them quickly identify bugs in their code.  If I'm creating Ipe files and I make a mistake, I definitely want Ipe telling me what's wrong with my output rather than silently ignoring some element.

From this point of view, this should be changed in svgtoipe.   As you say, this isn't easy, because svgtoipe is a rather simple script that doesn't fully parse the SVG before creating Ipe output - it rather translates elements on the fly (there are a few other things it can't do because of that).

**Comment by otfried** [comment]
If this is an actual problem for you right now, converting SVG figures to Ipe, I suggest writing a small script that simply filters out these path objects.  A simply regular expression match should do.

**Comment by pierreganty** [comment]
The command `xml ed -d  "//path[normalize-space(text())='0 0 m']" <file>.ipe` (using the xml utility [xmlstarlet](http://xmlstar.sourceforge.net/)) will delete every path of the form 
```xml
<path>
0 0 m
</path>
```
It would recommend it because it is safer to use than regular expression (e.g. it should always return a valid XML file)
