### ISSUE TITLE
Installing ipe interferes with already present texlive distro

### ISSUE THREAD

**Issue by fhchl** [otfried/ipe#167]
After installing ipe on my Ubuntu machine through `apt` I had problems using my standard TeXing setup (Sublime Text + LaTeXtools), because of the installed dependencies  `texlive-base texlive-binaries texlive-latex-base texlive-latex-base-doc`. These put multiple binaries directly into `/usr/local/bin` that where then used instead of the nicely separated files in `/usr/local/texlive/2017/bin/x86_64-linux/pdflatex`.

Is there any way to use the already present binaries with ipe or specify a different location for the installation of the dependencies, such that the install doesn't interfere with the present setup?

**Comment by otfried** [comment]
1. I have no influence on how Ubuntu packages Ipe.  If you dislike the packaging, you need to report the issue to Ubuntu.  By the way, the Ipe version packaged with Ubuntu is **ancient**, I no longer support it in any way.

2. Ipe will happily use any pdflatex on your system.  If it's on your PATH, then Ipe can use it.

3. The easiest solution to your problem seems to be to change your PATH so that `/usr/local/texlive/2017/bin/x86_64-linux/` appears **before** `/usr/local/bin`.  Then you don't have to change anything and your system should work fine again.

4. You can also uninstall the Ipe package and the installed dependencies, and use the Ipe AppImage instead (ipe.otfried.org -> Download the current Ipe version -> Linux AppImage).  This has the advantage that you have a state-of-the-art Ipe on your system.  Unfortunately it's slightly less convenient to run, see the explanation on the website.  

5. Alternatively,  uninstall the Ipe package and the installed dependencies, and compile Ipe yourself.  It's really easy on Linux: https://github.com/otfried/ipe-wiki/wiki/Downloading,-Compiling,-and-Installing-Ipe#debian-ubuntu-mint

6. Finally, you should be able to get `apt` to install the Ipe package **without** the dependencies. For instance, you can say `sudo apt download ipe`, which will download the two packages (`ipe` and `libipe`) that you can then install using `dpkg -i`.   But, as I said, this Ipe version is **ancient**, I don't recommend that you use it at all.

**Comment by fhchl** [comment]
Thanks for the detailed answer, otfried. As a matter of fact, the [Ubuntu package](https://packages.ubuntu.com/zesty/ipe) seems up to date. I filed an issue for Ubuntu. 

Using the AppImage works like a charm. Great little tool.
