### ISSUE TITLE
Duplicating endpoints of a spline gives weird splines

### ISSUE THREAD

**Issue by tinloaf** [otfried/ipe#168]
Hi, 

I'm using ipe 7.2.7. When I edit a spline, I can right-click one of its 'special' (i.e., pink) endpoints and duplicate it. Then I end up with two endpoints on that side of the spline, with the segment between them being just a straight line. It is then also impossible to delete that extra endpoint (because endpoints are protected from deletion, I guess?)

I think the correct behavior would be to create an "ordinary" control point instead of an endpoint, when the user duplicates an endpoint.

Thanks for ipe!
Lukas

**Comment by otfried** [comment]
An Ipe subpath is a sequence of pieces that are either straight segments, ellipse arcs, or B-splines.  The pink vertices are the points where the pieces join, that's why you can't simply delete one in this case.

A common operation one does on paths is to add a segment at the end.   If I make the change you suggest, then it would be impossible to add a straight segment at the end of a B-spline.   So there would be some real loss of functionality.

On the other hand, if you want to add an internal control point to a B-spline near the end, you can simply duplicate the second-to-last vertex and drag it to the end.   So the functionality you are asking for is already there.

Do I miss something?

**Comment by tinloaf** [comment]
No, you didn't. It's probably just differences in expectations how things work. If I wanted to add a straight segment at the end, I would not edit the spline, but rather draw the straight line and then use "join paths". But true, using the spline editor is another way of doing this. Sorry for the noise!
