### ISSUE TITLE
mouse button gets wrong number

### ISSUE THREAD

**Issue by lpb612** [otfried/ipe#17]
When using Ipe with Tablet Pens, sometimes the mouse button is reported as number 129, which should be 1. I don't know the reason for this, but the method MODEL:mouseButtonAction() is confused by this. The temporary solution is to map button 129 to button 1 in the beginning of the MODEL:mouseButtonAction(). But it would be nice to get to the bottom of the problem.

Other information: Xournal, another software that uses Tablet Pens, does not have the problem. The tablet I am using is Huion Tablet 6x10 Pro. Also,  'xinput test-xi2 --root' reports button 1, not button 129. Since 129=128+1, could it be that the 8th bit is set for some modifier, which should probably be ignored?
uname -a reports the following:
Linux nuc 4.1.2-2-ARCH #1 SMP PREEMPT Wed Jul 15 08:30:32 UTC 2015 x86_64 GNU/Linux

**Comment by otfried** [comment]
129 is a double click with the left mouse button.  It's normally only used in drawing mode, so there is no catch for it in MODEL:mouseButtonAction.

If you see it there and you did not double click, then it's probably the mouse driver or the Qt code that mis-interprets the pen movement (because of bouncing or something).  I'll have to map it to 1 in this case.

**Comment by lpb612** [comment]
It is likely an Qt problem, because xinput does not report double click, and xournal, which uses GTK does not have this problem. I will just map it to 1.

**Comment by otfried** [comment]
double-click events need to be requested, so you might not see them in xinput and xournal because they don't request them.  But I did not investigate this any deeper.
