### ISSUE TITLE
Resurrect IpePresenter

### ISSUE THREAD

**Issue by mrzv** [otfried/ipe#187]
It would be nice to resurrect and add IpePresenter to the main Ipe distribution. It was convenient for giving talks.

**Comment by mrzv** [comment]
One alternative on macOS is to use [Présentation](http://iihm.imag.fr/blanch/software/osx-presentation/). This works well but is missing Ipe's notes. If Ipe could save notes in the format that Présentation understands ([pdfcomments](https://www.ctan.org/pkg/pdfcomment/) package), it would solve this problem.

**Comment by otfried** [comment]
Saving the pages notes as a page annotation is a very good idea, independent of this use.

Implemented in 7.2.10.

**Comment by otfried** [comment]
The main question is how the page notes should appear in PDF viewers.  I'll try making them hidden for the moment.

**Comment by otfried** [comment]
A snapshot of a new Ipe build that saves page notes in the PDF annotations is available here:

https://www.dropbox.com/s/d6ygbv65nyxtk0n/ipe-7.2.9-mac.dmg?dl=0

Feel free to test the feature!

**Comment by mrzv** [comment]
Hm, this segfaults on me, when I try to save even a simple presentation (albeit one created with an earlier version of Ipe), even before I try to add notes. I haven't tested it extensively, but that seems like a serious problem to me.

**Comment by mrzv** [comment]
Here's the offending example: http://mrzv.org/tmp/presentation-template-16x9.pdf

Simply opening this PDF and then hitting save causes a segfault.

**Comment by otfried** [comment]
That was actually a completely unrelated bug - thanks for finding it before I release it!  :-)

Here is a fixed version:

https://www.dropbox.com/s/rqbnptoomiaxsxq/ipe-7.2.9-mac.dmg?dl=0

**Comment by mrzv** [comment]
The segfault is gone, but the notes don't show up in Présentation.

**Comment by otfried** [comment]
Strange - I just tried this version and it works for me with the current presentation.py script.

**Comment by mrzv** [comment]
I just double-checked, and it's not working here. Maybe the dropbox link is wrong?

**Comment by otfried** [comment]
List of PDF presenter software:

- https://bitbucket.org/rndblnch/osx-presentation/src  (OSX Python)
- https://github.com/pdfpc/pdfpc  (Gtk + Poppler)
- https://github.com/Cimbali/pympress/  (Python with Gtk and Poppler bindings)

pdfpc and pympress can apparently be compiled for Windows, but it doesn't look easy because of the reliance on Gtk.

**Comment by otfried** [comment]
> I just double-checked, and it's not working here. Maybe the dropbox link is wrong?

I made a mistake in the pdfwriter that caused an illegal object reference, and apparently the PDF parser on El Capitan simply ignored that while the newer one aborts reading the annotations.

It should be fixed now in 7.2.10.

There is still something strange:  When I open the PDF file produced by Ipe in Preview, I can see an annotation icon in the bottom left corner - but clicking on it shows me an empty annotation, instead of the text that should be there.   And apparently Preview then silently modifies the file, deleting the annotation that was there.   

But I guess everyone knows by now that one needs to be careful with OSX Preview on Ipe PDF documents.

**Comment by mrzv** [comment]
Oh, man, I didn't know that. Good to know. I'll test out the new version as soon as I get to my computer. Thanks!

**Comment by mrzv** [comment]
Just to close the loop on this. I tested the notes with Ipe 7.2.10, and they show up in Présentation. So it's all good. Thanks!
