### ISSUE TITLE
"undo" does not work in 7.2.9 on macos

### ISSUE THREAD

**Issue by MoniqueTeillaud** [otfried/ipe#212]
Hi Otfried,
I have macos High Sierra 10.13.6, ipe 7.2.9 installed from dmg. 
* "Apple Z" has no effect
* in the menu Edit, "undo" appears as lightgrey, i.e. it is disabled.
Fortunately I had kept the dmg for 7.2.7 in Trash, I reintalled it :)
Best,
Monique

**Comment by nathaniel** [comment]
I just discovered the same issue in Ipe 7.2.8. Undo works fine in both versions (7.2.8-7.2.9) in Windows 64 bit.

**Comment by otfried** [comment]
Getting undo/redo to work correctly is quite tricky on OSX.   To make undo/redo available in dialog text fields, you need to use the Cocoa actions "undo" and "redo", but if you implement them on the responder chain for your own window, then Cocoa assumes one is using an NSUndoManager and relies on that to check if undo/redo is available.

Undo stopped working in Ipe because I had enabled it for text fields (and it is working there now).

I have now implemented a work-around, where I'm using separate edit menu entries for the undo/redo in Ipe itself and in dialog fields.   The drawback is that one needs to use different keyboard shortcuts.

Please test if this is usable;
https://www.dropbox.com/s/rqbnptoomiaxsxq/ipe-7.2.9-mac.dmg?dl=0

**Comment by nathaniel** [comment]
The new version works for me. It is indeed odd to have to use different
menu entries/keyboard shortcuts for Undo/Redo depending on whether a dialog
field is currently in focus.

Nathaniel

**Comment by otfried** [comment]
Fixed in 7.2.10.
