### ISSUE TITLE
Undo of text changes is not shown

### ISSUE THREAD

**Issue by christiankral** [otfried/ipe#223]
Consider the following case: 

- Create a new text either by *Text labels* or *Mathematical symbols*
- Enter the text and press OK
- Select the text, make a right click on the text, pick *Edit text* 
- Change the text and press OK
- Hit CTRL+Z to undo change

The text change is performed but not shown. When saving the file and re-opening it, the changed text is shown correctly.

This issue applies to IPE 7.2.10 under Linux Mint 19, 64bit (based on Ubuntu 18.04).

**Comment by otfried** [comment]
Just use Ctrl+L to run Latex.

The mode "Automatically run Latex" (which you have activated in the File menu) is meant to save you a few key presses, but it doesn't do everything.    Since running Latex is relatively slow compared to other operations, Ipe only does it when it is sure it is necessary.

Undo, redo, and pasting objects may or may not need a Latex run, depending on the operation or the objects being pasted.   Perhaps I can try to make it a bit more clever, but it really is just a single key press that you would save.

**Comment by otfried** [comment]
Notes if I ever want to make Ipe smarter in this respect:

- paste and paste_at need to scan the pasted elements if they contain a text (possibly inside group). 
- undo items should carry a "runlatex" attribute.
- undo and redo run latex if the attribute is set.
- operations that currently run latex only set the flag (edit text, insert text, transform text)...

Another option is to implement running latex in the background so that it's not such an interruption, and then starting a new latex run in any operation that could possibly need it.

**Comment by christiankral** [comment]
Thanks for your feedback. The additional keystroke is OK; I just didn't know that CTRL+L solves my problem.
