### ISSUE TITLE
tonumber never returns nil

### ISSUE THREAD

**Issue by jlvermeulen** [otfried/ipe#236]
I'm trying to write a small ipelet for which the user needs to provide a number. I am using `model:getString()` to get the input, followed by using `tonumber()` to convert it into a numeric value. According to Lua's documentation, this should return `nil` if the provided string does not represent a number. However, in Ipe it seems like tonumber returns `0.0` for any non-numeric string:

    model:warning(tostring(nil))     -- prints nil
    model:warning(tonumber("bla"))   -- prints 0.0

This breaks the standard logic for testing a succesful parse, something like

    local xstr = model:getString("Enter value of x:")
    local xnum = tonumber(xstr)
    if not xnum then
        model:warning("Not a valid input.")
    end

I considered that this might be an issue with Lua, but testing in online editors running version 5.3.x shows that the above should work.

**Comment by otfried** [comment]
Ipe overrides the `tonumber` function, because the Lua implementation is locale dependent and we used to have several bugs because of locale-dependent number conversions.

The built-in Ipelets check input strings using pattern matching, something like this:
```
    local str = model:getString("Enter delta")
    if not str or not str:match("^[%+%-%d%.]+$") then return end
```

But I agree with you that it would be better if `tonumber` behaves like the original Lua function, so I'll fix this in the next release.
