### ISSUE TITLE
Structuring of symbols

### ISSUE THREAD

**Issue by christiankral** [otfried/ipe#237]
I started to work on symbol library for electrical engineering components in https://github.com/christiankral/ElectricalEngineering.isy

![image](https://user-images.githubusercontent.com/4184218/55566861-d530c000-56fc-11e9-8ed6-6b7865949d58.png)
 
In order to better work with the library it were quite beneficial to be somehow able to structure the symbols by sub structures (like directories). So far I used the slash `/` to structure the symbols as it is applied for the standard symbols. But by now the list far too long to fit on one screen page. 

Is there a proposed way to structure the symbols with the current version of IPE?

**Comment by otfried** [comment]
It would be quite easy to change the Ipelet so that you can select symbols by group.  I'll have a look at that when I have some free time.

As far as I can tell, you are the first one to try to make a larger library of Ipe symbols.   There are others who have made Ipe libraries, but they simply created an Ipe document with their drawing library, and they copy and paste the parts they need into their current document.

Currently Ipe symbols are somewhat limited, because Ipe will not snap to points inside a symbol.   So for instance you cannot connect wires to the two ends of a resistor.   This seems like one of the main features needed to make symbols more interesting.

Currently Ipe symbols are more or less only used for markers and as page backgrounds in presentations.

**Comment by otfried** [comment]
I have updated the ipelet so that it will offer the symbols in groups (you select the group first, then the symbol).

Unfortunately implementing this required a change in the ipeui library (to update the symbol selector when the group changes), so it will be in the next release.

**Comment by otfried** [comment]
Implemented in 7.2.12.
