### ISSUE TITLE
Feature request: Edit text object dialog box

### ISSUE THREAD

**Issue by mmnich** [otfried/ipe#263]
It would be great if the dialogue box "Edit text object" would allow selecting all text via the Ctrl+A keyboard shortcut, as well as closing the dialogue box using the Esc keyboard shortcut.

**Comment by otfried** [comment]
Are you on MacOS?   Ctrl+A seems to work on Windows and Qt.

**Comment by mmnich** [comment]
First, let me say that ipe is really awesome for making presentations. My suggestion was just meant to speed up the workflow by using the keyboard more effectively, instead of always switching to the mouse for selecting text.

I use Windows 8.1, and Ctrl+A does not work in either the "Edit text object" dialogue box or the "Edit page title and sections" dialogue box. The usual shortcuts Ctrl+C and Ctrl-V for copying and pasting work, though.

**Comment by otfried** [comment]
Which version of Ipe are you using?

I now checked on my Windows 10 laptop:  When I open the Edit text dialog using Ctrl+E and then immediately press Ctrl+A, it selects the entire text.   In the "Edit page title and sections" box, the text in the "page title" field is in fact already selected.

Did this really change so much between Windows version?    Which keyboard layout are you using?

**Comment by mmnich** [comment]
I am using Ipe 7.2.12.

I tried different keyboard layouts, like German and English, but it does not make a difference; Ctrl+A does not work in either case.

The Esc key does close the "Edit page title and sections" box, but does not close the "Edit text object" box.

**Comment by otfried** [comment]
I don't know what to do about the Ctrl+A key.   It works in Windows 10, and I don't have Windows 8.1 to test with.  In any case, the key is handled by Windows - Ipe just creates a text box.

That the Esc key does not close the dialog is deliberate, because too many people have lost their edits by accidentally pressing Esc.

If you don' t like this, open `tools.lua` and find the function `MODEL:action_edit_text`.  Inside, change the line
```
  d:set("ignore-escape", true)
```
Use `false` instead of `true` or remove the line completely.

I will look into checking if we can allow Esc to close the dialog if the text has not been touched yet (would that be good enough for you?).

**Comment by mmnich** [comment]
Great, many thanks for the proposed workaround of editing the tools.lua. That's good enough for me.

Your suggestion of allowing Esc to close the dialog if the text has not been touched yet sounds pretty sophisticated...indeed a good suggestion for the future.

Many thanks again.

**Comment by otfried** [comment]
Implemented in 7.2.15.
