### ISSUE TITLE
version 7.2.13 quit unexpectedly on Mac

### ISSUE THREAD

**Issue by sanjaymath** [otfried/ipe#272]
I have installed version 7.2.13 on my Macbook (running on OS X Yosemite 10.10.5), but it quits unexpectedly with an error message when I try to launch it. I tried to uninstall and reinstall, still the same.

I then uninstalled version 7.2.13 and installed version 7.2.7 instead, the latter works well. The problem is that I cannot open with version 7.2.7 the files that I created on my desktop computer with version 7.2.13.

Thanks in advance.

**Comment by otfried** [comment]
What is the error message you get?

**Comment by otfried** [comment]
When exactly did you download the ipe-7.2.13-mac.dmg file?   Did you try ipe-7.2.12-mac.dmg as well?

**Comment by sanjaymath** [comment]
Hi Otfried, thanks for the quick answer, and for developing this software in general !

I downloaded the ipe-7.2.13-mac.dmg file half an hour before the message I initially posted.

The app opens for half a second then shuts down and there is an error message showing up. It is in French as my laptop is in French. There is a yellow triangular warning sign with an exclamation mark, the title is something like "Ipe quit unexpectedly" and the content is : "Click on Reload to re-open the app. Click on Report to get more details and send a report to Apple." You have the choice between three buttons to click at the bottom, Ignore, Report or Reload.

I have just tried older versions of Ipe for Mac, versions 7.2.12 and 7.2.11 also crash the same way, but version 7.2.10 works well. Hope it helps you to locate the bug !

**Comment by otfried** [comment]
Can you press the "Report" button?  It will create a window containing a long error message.  It would be helpful if you can copy and paste this error message (you don't need to press the "Send to Apple" button that comes afterwards).

**Comment by otfried** [comment]
I could reproduce the problem on my old laptop running El Capitan.

I built Ipe again on that computer, and it works fine.   You can download this version here:

https://www.dropbox.com/s/dizia73vrh5xlby/ipe-7.2.13-mac.dmg?dl=0

I will investigate what the problem is.  I'm suspecting it may be one of the dependencies.

**Comment by sanjaymath** [comment]
That version worked also with me, thank you very much for your help !

**Comment by otfried** [comment]
For the moment, I'm publishing versions compiled on El Capitan.   I still need to figure out why the newer compilations crash on older hardware.

**Comment by otfried** [comment]
I've finally figured out what caused this.   Starting from 7.2.15 I can build a single binary again 😄

**Comment by dinesh-krishnamoorthy** [comment]
I am having the same issue. I am using MacOS Monterey and ipe v7.2.26. (see error message below). Any help will be appreciated.

------------------------------------------------------------

Process:               ipe [66904]
Path:                  /Applications/Ipe.app/Contents/MacOS/ipe
Identifier:            org.otfried.ipe.Ipe
Version:               7.2.26 (7.2.26)
Code Type:             X86-64 (Translated)
Parent Process:        launchd [1]
User ID:               503

Date/Time:             2023-03-27 00:39:51.8725 +0200
OS Version:            macOS 12.6 (21G115)
Report Version:        12
Anonymous UUID:        85D5AC5D-5AEB-0B54-2873-14FCC57E042A


Time Awake Since Boot: 290 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Application Specific Information:
abort() called

**Comment by otfried** [comment]
Does this happen directly after starting Ipe?

I do not have access to hardware that can run Monterey, or that have the M1/M2 chips, so I cannot help here.  You'll either have to compile Ipe yourself and debug, or wait for an Apple user with new hardware to jump in.

**Comment by otfried** [comment]
And please open a new issue so other's can see it and perhaps help.

**Comment by dinesh-krishnamoorthy** [comment]
Dear Otfried,

Thank you for your reply.

Just a little background. It was working in my machine just fine, until yesterday, when all of a sudden ice crashed, and now it wouldn’t open. 
I tried clearing the cache, updating my OS, reinstalling ipe, but the issue persists.

When I run ipe.exec this is what I get, if this makes any sense to you.


(base) ***@***.*** ~ % /Applications/Ipe.app/Contents/MacOS/ipe ; exit;
/Applications/Ipe.app/Contents/Resources/lua/model.lua:685: bad argument #1 to 'setRecentFiles' (argument is not a table)
stack traceback:
	[C]: in method 'setRecentFiles'
	/Applications/Ipe.app/Contents/Resources/lua/model.lua:685: in method 'updateRecentFiles'
	/Applications/Ipe.app/Contents/Resources/lua/model.lua:83: in method 'init'
	/Applications/Ipe.app/Contents/Resources/lua/model.lua:14: in method 'new'
	/Applications/Ipe.app/Contents/Resources/lua/main.lua:489: in main chunk
	[C]: in function 'require'
	[string "require "main""]:1: in main chunk

Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.


[Process completed]
