### ISSUE TITLE
eps file scaling is wrong after export

### ISSUE THREAD

**Issue by ghost** [otfried/ipe#275]
Hi,
when I draw two schematics, which are scaled exactly the same in ipe (for example one inductor is 32 pts wide in the two schematics in the attachnments), and I export them as eps, the inductor will have different sizes when I open the eps files with Illustrator or use them in Latex.

In this example in one eps file it will have the width of 16.9mm, in the other it has 18.9mm.

This looks very bad when I place the schematics side by side.

Unfortunatelly this bug doesn't appear every time I save, I could not yet find out when it appears and when not. But has anyone noticed the same behaviour?

Best,
Christoph

[schaltungen_ipe_and_eps.zip](https://github.com/otfried/ipe-issues/files/3911186/schaltungen_ipe_and_eps.zip)

**Comment by otfried** [comment]
Did you generate the eps files using "Export as EPS" from the File menu?

It turns out that this obeys the **current zoom** setting of the canvas, so if you did not zoom to the same setting, you'll get different scaling in the output.

I will fix this - only PNG output should be scaled depending on zoom, SVG and EPS should of course have the original coordinates!

**Comment by otfried** [comment]
So for the moment:  Just use Zoom -> Normal size before you export.

**Comment by otfried** [comment]
Fixed in 7.2.15.
