### ISSUE TITLE
Windows: Retain arrangement of toolbars after closing IPE

### ISSUE THREAD

**Issue by pglira** [otfried/ipe#28]
It seems that since IPE 7.1.7. an individual arrangement of toolbars is not saved when IPE is closed.

My wanted layout:
![2015_11_24_14_02_18](https://cloud.githubusercontent.com/assets/14214284/11367513/74203b0c-92b4-11e5-8ebd-a8d73bfe5c12.png)

After a restart of IPE:
![2015_11_24_14_02_26](https://cloud.githubusercontent.com/assets/14214284/11367517/78b368f6-92b4-11e5-8bcc-df5d8b578b3f.png)

**Comment by otfried** [comment]
Please indicate the platform when you file a bug report.  I assume you are on Windows?

Since 7.1.7, Ipe uses a native UI on Windows, which does not save any state.  Actually I never implemented any state saving for the toolbar, but perhaps Qt did that automatically.

Is it just the order of toolbars that you want to change?  That could easily be a preference.

**Comment by pglira** [comment]
Yes, it's Windows 7. If it would be possible, I would change order and size of the toolbars (as can also be seen in the screenshots of my previous post).

**Comment by otfried** [comment]
That version is ancient anyway.

**Comment by otfried** [comment]
In 7.2.4 you can set

```
prefs.toolbar_order = { "edit", "grid", "angle", "mode", "snap" }
```
