### ISSUE TITLE
Missing menu bar

### ISSUE THREAD

**Issue by marcelrad** [otfried/ipe#29]
I installed the latest ipe version on my system (7.1.10) and I am missing the menu bar completely. I work with ubuntu 14.04 with gnome shell 3.10 and qt5 installed. 

![screenshot from 2015-11-24 17 43 09](https://cloud.githubusercontent.com/assets/458451/11373543/16766764-92d3-11e5-976b-26892f2519fa.png)

**Comment by otfried** [comment]
Did you compile Ipe yourself?

My understanding is that Gnome 3 is trying to imitate Mac OS and puts the menu bar at the top of the screen.  It's not there by any chance?  It could be that this "feature" of Ubuntu/Gnome 3 is breaking the menu bars.  (That's one of the reasons why I stopped using Ubuntu and switchted to Mint.)

**Comment by marcelrad** [comment]
Yes, I did compile it myself.

Unfortunately, I could not find the menu bar anywhere.

![screenshot from 2015-11-25 09 12 58](https://cloud.githubusercontent.com/assets/458451/11391743/0b3f6f94-9355-11e5-8596-8710916393b5.png)

**Comment by otfried** [comment]
Well, then there seems to be something wrong on your system.

I assume you had no problem with the previous Ipe version?   Then you should try simply compiling 7.1.10 with Qt 4 instead of Qt 5.

Change the settting of QT_CFLAGS and QT_LIBS back to Qt4 and make sure you are using the moc for Qt4 (check with moc -v, maybe you have to call it as moc-qt4, or set the environment variable QT_SELECT=4):

QT_CFLAGS     ?= $(shell pkg-config --cflags QtGui QtCore)
QT_LIBS            ?= $(shell pkg-config --libs QtGui QtCore)

**Comment by marcelrad** [comment]
Thanks, the menu bar is back with QT4.

**Comment by ben-strasser** [comment]
This is not an issue with IPE but with the combination QT 5 & Ubuntu without Unity. You can solve it by uninstalling the following package: 

sudo apt-get remove appmenu-qt5

**Comment by otfried** [comment]
I am now running Ubuntu 14.04 myself, and still could not reproduce the problem.

Does it also go away if you simply go to Settings -> Appearance -> Behaviour and set the menu to be in each Window (rather than at the top of the screen)?

**Comment by ben-strasser** [comment]
Hi,

On 04/12/2016 01:12 PM, Otfried Cheong wrote:

> I am now running Ubuntu 14.04 myself, and still could not reproduce the
> problem.

are you using Unity? I'm using Gnome classic. Do you have appmenu-qt5 
installed?

I'm pretty sure that this is the same problem as described here

https://bugs.launchpad.net/ubuntu/+source/appmenu-qt5/+bug/1307619

> Does it also go away if you simply go to Settings -> Appearance ->
> Behaviour and set the menu to be in each Window (rather than at the top
> of the screen)?

This option has no effect for me. This could very well be because I 
uninstalled appmenu-qt5.

Best Regards
Ben Strasser
