### ISSUE TITLE
Feature request: Automatic export to pdf/png/...

### ISSUE THREAD

**Issue by doppelhammer** [otfried/ipe#296]
It would be great if one could activate the option "Automatically export to png (into the same directory as the ipe-file) upon save" and the same for png, eps.

By the way:
Thanks for your great work on IPE!!!!!!!!!!!!! ### Since I use it quite often und with fun doing that, I support your work with small mount financially...

**Comment by otfried** [comment]
Here is an ipelet that will enable auto-export to all formats.

Just place the file `autoexport.lua` in one of your ipelet folders:

[autoexport.lua.zip](https://github.com/otfried/ipe-issues/files/4545115/autoexport.lua.zip)

You will need to select the formats you want to export to, and the resolution (pixels-per-inch) for the PNG export.   Except for pdf, the export will only use view 1 of page 1.

I'm a bit hesitant to make this part of Ipe, because all these other formats do not support multi-page documents, so I'm sure this will confuse users.

**Comment by otfried** [comment]
I've decided to include it in the next release 7.2.16.

**Comment by doppelhammer** [comment]
How can one activate the "auto-export"?

**Comment by doppelhammer** [comment]
That was fast (implementing the feature and releasing a new version!) Thanks!

**Comment by otfried** [comment]
In 7.2.16, make a customization file (http://ipe.otfried.org/manual/manual_customize.html) and put the line
```
prefs.auto_export = { "png", "eps" }
```
(List the formats you want.)

It's documented in `prefs.lua`, like all other preferences.
