### ISSUE TITLE
Transparency becomes Black

### ISSUE THREAD

**Issue by TillBerlin** [otfried/ipe#328]
I insert a picture using ctrl+v and all the transparency becomes black. :(
I made a video showing what I did.

https://youtu.be/5yqkrc79LQs

I just downloaded IPE 7.2.18 .
Many Thanks and keep up the good work. :)

**Comment by otfried** [comment]
The Windows clipboard is a huge mess.   There is no standard way to store images there, so for maximum compatibility many programs write various different formats, in the hope the receiver can decode one of them.

Ipe can understand transparency only when the producer includes a PNG version of the bitmap.  Word and Powerpoint do that, but apparently the Photos app does not.   If you copy your picture in Photos, then paste it into Word, copy it in Word, and paste it into Ipe, it will work.

Your specific case looks like it might be easy to support, because the Photos app places both the name of the image file and its contents on the clipboard, so Ipe might be able to either read the file itself or to use the FileContents data.

**Comment by TillBerlin** [comment]
OK, I tried the MSword workaround and it did the job. :)
Let me remark that copying pictures into ipe, worked in version 7.2.12.
Can you recommend a program with which I could open the .png files instead? 
I use this feature a lot, so the MSword workaround is a little painful.
many thanks for your help. :)

**Comment by otfried** [comment]
Pasting images into Ipe has been available for many years, but without transparency.   In fact, support for transparent images in Ipe was only added in 7.2.12, and pasting images with transparency on Windows was implemented only in 7.2.17.  

As I don't use Windows myself, I have no good suggestion for what other image viewer would work.  But if you have the image as a file on your computer already, why don't you simply use "Insert Image" (Ctrl+Shift+O) ?

**Comment by otfried** [comment]
Here is a new version where copying images with transparency will work when copying from Photos.  In fact, you can now copy images directly from the navigator (the file browser), you do not even need to open them at all.

[ipe-7.2.18-win64.zip](https://github.com/otfried/ipe-issues/files/4752045/ipe-7.2.18-win64.zip)
