### ISSUE TITLE
On MacOS, ipe 7.2.18 doesn't change the color of text after I've modified it

### ISSUE THREAD

**Issue by saschawolff** [otfried/ipe#333]
The text color does change, when I press cmd+L in order to call LaTeX.

**Comment by otfried** [comment]
I also noticed this recently.     Do you have any idea when this stopped working?   I used to use a trick to make it possible to change the color without rerunning Latex, but had to get rid of that quite a while ago.

Maybe the cleanest solution is to automatically run Latex when you change the color of a text object.

**Comment by saschawolff** [comment]
Dear Otfried,

> I also noticed this recently. Do you have any idea when this stopped
> working?

I think it was very recently, I'd say with ipe 7.2.{17,18}.

> I used to use a trick to make it possible to change the color without
> rerunning Latex, but had to get rid of that quite a while ago.

:-(

> Maybe the cleanest solution is to automatically run Latex when you 
> change the color of a text object.

sure.  can the user enable this behavior, or does this need to be
coded?

jonathan complained that the LaTeXing in the background recently
made his Windows-Ipe much slower.  maybe this asks for customization?

sascha

**Comment by otfried** [comment]
Apparently I have been releasing too often - you got confused about what's "recent" :-) 

The last version where it worked was 7.2.14, and it worked because Ipe did automatically run Latex after a color change.

To fix it, find the function `MODEL:selector` in `actions.lua` (Reminder: no compilation necessary), and change the line
```
    if prop == "textsize" and has_text(self:page()) then
```
to
```
    if prop == "textsize" or has_text(self:page()) then
```
I'll release a new version soon.

**Comment by otfried** [comment]
Can you get Jonathan to file a bug report and explain what is slow?

Ipe doesn't really run Latex in the background - it only keeps the UI event loop active while Latex is running.   The only reason I can see for this to be slower than before is because Windows needs a moment to show the small modal dialog - is that what he means?

If I know what the problem is, I can try to fix it (e.g. delay showing the dialog for half a second, so that it doesn't show if Latex is fast) - but I can't do that if nobody tells me about it.   I nearly never work on Windows or OSX myself.

**Comment by saschawolff** [comment]
Dear Otfried,

the fix does indeed the job! – Thanks a lot.

Maybe it would make sense to call LaTeX also in case the user does an undo
(ctrl+z), for the same reason.

Sascha

**Comment by otfried** [comment]
I have been hesitant to automatically run Latex in situations where it *might* be necessary:  copy + paste and undo/redo.     Running Latex isn't always a fast operation, and pressing Ctrl+L is quite easy.

Unfortunately, more and more new Ipe users don't know that it is ultimately their job to run Latex when needed (in fact, they don't even know it's possible), and that the "Automatically run Latex" is just an optimization (see e.g. #223, #224, #249, #330).    So I guess it's time Ipe does it in those situations.

**Comment by otfried** [comment]
Can you ask Jonathan to try this version and see if it fixes the slowness?  (And if not, to create an issue and explain?)

[ipe-7.2.18-win64.zip](https://github.com/otfried/ipe-issues/files/4758721/ipe-7.2.18-win64.zip)

**Comment by joklawitter** [comment]
The problem was that when a text element was selected and you clicked on any of the dropdown menues, that ipe slowed down or even froze for 1-3 seconds (depending on the size). But yes, the problem is gone in 7.2.18! Thanks :)

**Comment by otfried** [comment]
Great - I'll release the new version in the weekend.
