### ISSUE TITLE
Dropdown Boxes not reacting

### ISSUE THREAD

**Issue by thobl** [otfried/ipe#341]
Since recently, the dropdown boxes (for changing object properties or grid size) stopped working. They still slightly light up when hovering, but clicking has no effect. This only affects the main window. Dropdown boxes in dialog windows (e.g. font size in the label dialog or Latex engine in the Document properties) do work.

I cannot tell when exactly the issue started occurring, but it was definitely present for Ipe 7.2.19 and 7.2.20 did not fix it.

I am on Arch Linux and have Ipe installed via AUR. Here are the libraries ipe uses:

> Ipe relies on the following fine pieces of software:
> 
>  * Pdftex, Xetex, or Luatex
>  * Lua 5.3 (1488 kB used)
>  * The font rendering library Freetype 2.10.2 / 2.10.2
>  * The rendering library Cairo 1.17.3 / 1.17.3
>  * The clothoid spline library libspiro 20190731
>  * The GUI toolkit Qt 5.15.0 / 5.15.0
>  * The compression library zlib 1.2.11

**Comment by otfried** [comment]
That is strange.   I don't have Qt 5.15 myself - it could be that something has changed in Qt.   But if the issue has started to appear in 7.2.18, then my guess is that it is caused by a platform theme.   Ipe used to disable those, but I removed that in 7.2.18.

You could try to see if the environment variable QT_QPA_PLATFORMTHEME is set on your system (and try unsetting it before starting Ipe).

**Comment by thobl** [comment]
QT_QPA_PLATFORMTHEME is set to "gtk2" and unsetting it does not resolve the issue.

I just downgraded the qt5-base package to 5.14 and reinstalled ipe with it.

> * The GUI toolkit Qt 5.14.2 / 5.14.2 

With this, the dropdown menus work again but all icons are somehow missing (e.g., all the tool buttons are blank). I guess this comes from the fact that my Qt installation is not very consistent when I just downgrade the qt5-base package. Upgrading qt5-base without reinstalling ipe gives me back the icons but also breaks the dropdown menus. 

> The GUI toolkit Qt 5.14.2 / 5.15.0

So I would guess that something changed from Qt 5.14 to Qt 5.15 that breaks the dropdown boxes.

Also: During compilation, I got several deprecated-warnings. For example: 
```
main_qt.cpp:128:41: warning: ‘const QRect QDesktopWidget::screenGeometry(int) const’ is deprecated: Use QGuiApplication::screens() [-Wdeprecated-declarations]
  128 |   QRect r = a.desktop()->screenGeometry();
      |                                         ^

appui_qt.cpp:759:34: warning: ‘void QListWidgetItem::setTextColor(const QColor&)’ is deprecated: Use QListWidgetItem::setForeground() instead [-Wdeprecated-declarations]
  759 |       item->setTextColor(Qt::blue);
      |                                  ^

appui_qt.cpp:789:40: warning: ‘QString& QString::sprintf(const char*, ...)’ is deprecated: Use asprintf(), arg() or QTextStream instead [-Wdeprecated-declarations]
  789 |   s.sprintf("(%dppi)", int(72.0 * zoom));
      |                                        ^
```
Not sure whether this could have something to do with the issue.

**Comment by otfried** [comment]
Strange.   I fixed the deprecation warnings in ipeui_qt.cpp after I discovered them when compiling Linux packages for Ubuntu 20.04 on the Suse build service - but I never saw these in appui_qt.cpp.

As for the tool buttons not showing, it's most likely because qt5-svg got uninstalled when you downgraded.    The tool buttons are now in SVG format, so you need the Qt svg module.  

I'll see if I can install Qt 5.15 somewhere to debug the problem.

**Comment by thobl** [comment]
I can confirm that also downgrading qt5-svg to 5.14 resolves it. So this is a temporary fix for me but it is of course not optimal.
Thank you for looking into it!

**Comment by otfried** [comment]
Arch Linux users are always the first ones to have to debug Qt-problems.     That's the benefit of running a distribution that always has cutting-edge versions of everything.

**Comment by otfried** [comment]
Reading the paragraph about QGtkStyle in 

https://wiki.archlinux.org/index.php/Uniform_look_for_Qt_and_GTK_applications

makes me strongly suspect the platform theme as a possible culprit.    Could it be that when you downgraded to 5.14, you also disabled qt-styleplugin and disabled the platform theme?

You did try starting Ipe from the command line after unsetting the environment variable, e.g. with 
```
unset QT_QPA_PLATFORMTHEME && ipe
```
?

**Comment by thobl** [comment]
Yes, I tried unsetting QT_QPA_PLATFORMTHEME (and retried with your exact command), which did not help.

Concerning downgrading: I just downgraded qt5-base (and later additionally qt5-svg). As far as I know this does really downgrade only this package and not even touches dependencies.
Concerning qt5-styleplugins specifically: I did not have this package installed at all. I just installed it to see whether it changes something and I can report that it makes ipe look very different but unsetting QT_QPA_PLATFORMTHEME makes it look as it always does. The dropdown boxes don't work in either case though.

**Comment by otfried** [comment]
Thanks for the experiments, so it's good to know it's not the platform theme.

To be honest, my experience with bugs reported by Arch Linux users is that the best strategy for me is to just wait until the bug is fixed upstream...

**Comment by thobl** [comment]
It seems like the issue comes from the `setFocusPolicy(Qt::NoFocus)` in lines 298, 299, and 416 of src/ipe/appui_qt.cpp.

I am not sure what this is supposed to do, but commenting out the above three lines fixes the issue.

**Comment by otfried** [comment]
Thanks for debugging the problem.   So it's clearly a Qt bug:  there is no reason why not allowing the widget to get keyboard focus should stop it from reacting at all.   Will you post a bug report to Qt?

The reason for the focus policy call is that clicking on the selector would give it keyboard focus, and then keys would go to that widget instead of the main window, which is responsible for interpreting the keyboard shortcuts.   You don't have the problem that shortcuts like 'p' or 'l' stop working after you used a selector?

**Comment by thobl** [comment]
I created a bug report: https://bugreports.qt.io/browse/QTBUG-85510

The shortcuts still work as intended. After clicking on a selector, I can use the arrow-keys to change the value (I assume this is not possible with setFocusPolicy(Qt::NoFocus)), but all other shortcuts like 'p' and 'l' go correctly to the main window and change the selected tool.

**Comment by otfried** [comment]
That is excellent news.   I've just tested on Qt 5.9 that setting the `NoFocus` policy is no longer necessary to keep shortcuts working, so I will just remove the three lines.
