### ISSUE TITLE
Arrows on polylines

### ISSUE THREAD

**Issue by Ted102J** [otfried/ipe#352]
When adding arrows to polylines both forward and reverse arrows appear in properties window but only reverse arrow appears on figure. If the polyline is editted as XML only the rarrow is present. If this is editted to farrow the rarrow disappears from figure but farrow does not appear. On reopening XML the farrow reference has gone. (Kubuntu 20.04, ipe 7.2.20)

**Comment by otfried** [comment]
Can you please attach the file or at least the XML representation of the object in question?   Without that, how do you expect me to investigate your problem?

**Comment by Ted102J** [comment]
My apologies. I am new to all this. I am a great fan of you program. Is this file sufficient? I could not add forward arrows to the straight lines.

[f2.zip](https://github.com/otfried/ipe-issues/files/5307961/f2.zip)

**Comment by otfried** [comment]
There's a very simple solution to the puzzle :smile: 

If you look at the XML for your path, it looks like this:
```
<path stroke="black" rarrow="normal/normal">
288.372 695.647 m
161.614 559.589 l
161.614 559.589 l
</path>
```
As you can see, the last vertex of the path is duplicated.   That means, the last segment of the path has zero-length, and Ipe will refuse to attach an arrow to a zero-length segment, because that has no direction.

You probably terminate your path by left-clicking to place the vertex and then right-clicking.   But actually right-clicking doesn't just terminate the path, it also places the final vertex.

If you remove one of the duplicate lines, it will work.
