### ISSUE TITLE
Font problems in Ubuntu 20.04

### ISSUE THREAD

**Issue by wolfris** [otfried/ipe#355]
Hi,
when using fourier or palatino fonts in IPE with \usepackage[T1]{fontenc} in Ubuntu 20.04, text is not displayed (a series of boxes is shown). Normal LaTeX documents (pdftex) work well with these fonts.

![Screenshot from 2020-10-28 15-00-54](https://user-images.githubusercontent.com/6311666/97477439-67776500-192e-11eb-9178-48995520fdef.png)

The pdf I am working on was created on Ubuntu 18.04, where it works fine.

Any ideas of what the reason for this behaviour could be?

**Comment by otfried** [comment]
Can you attach a sample document that exhibits this problem?

**Comment by wolfris** [comment]
Document attached. Thanks

[SampleDoc.pdf](https://github.com/otfried/ipe-issues/files/5455136/SampleDoc.pdf)

**Comment by wolfris** [comment]
I just realized that it renders the text just fine in the pdf file. It's in the ipe environment that I can't see it.

**Comment by otfried** [comment]
If I open the PDF file with ipepresenter, it shows this message:

![image](https://user-images.githubusercontent.com/9983417/97535163-7e17cd80-19bb-11eb-992c-89a3736df09f.png)

Didn't you get the same message in Ipe?   It explains exactly what the problem is - your Latex installation is missing proper fonts for the font families you selected, and is using bitmaps instead.

Try installing the `cm-super` package and see if that solves the problem.

(On my own computer with Mint 20, which is more or less Ubuntu 20.04, your file works fine in Ipe.)

**Comment by wolfris** [comment]
Hi Otfried,
I did not get this message from Ipe. But it was, indeed, the problem. Installed cm-super and it now works fine.

Thank you very much!!
