### ISSUE TITLE
ipe.exe does not execute

### ISSUE THREAD

**Issue by JPM1966** [otfried/ipe#358]
Hi,
I am a Windows 10 user. I have been using ipe for years, it worked great.  Since today, clicking on ipe.exe does not produce anything. No window opens, no complain from the operating system. I have tried to re-install. Installing the last version of ipe (both 64 and 32 bit versions) does not solve the problem either.

**Comment by otfried** [comment]
I have just tried downloading the newest Ipe version on a Windows computer, with all Windows 10 updates applied.   It works just fine for me.

Could it be that your anti-virus software stops Ipe from running?

Otherwise, you could open a command window (Windows+R, then type "CMD") and run Ipe from there to see if you get any error message.
