### ISSUE TITLE
IPE-generated pdf can be read in 7.2.5 but not in 7.2.13,18, 23

### ISSUE THREAD

**Issue by mkraska** [otfried/ipe#372]
IPE refuses to open the following IPE-generated file in versions 7.2.13, 7.2.18, 7.2.23. It can, however, opened in 7.2.5.
I have multiple files which won't open with recent versions, this one, however, has been tested with older ones.

[Schnittlastenverlauf.pdf](https://github.com/otfried/ipe-issues/files/5892585/Schnittlastenverlauf.pdf)
![grafik](https://user-images.githubusercontent.com/12987918/106249237-65b18c00-6212-11eb-96bd-443fcc347b44.png)

**Comment by otfried** [comment]
When Ipe shows you a parsing error, your best bet is to look into the file yourself.  Run `ipeextract Schnittlastenverlauf.pdf` to produce `Schnittlastenverlauf.xml`.  If you open that file and look at position 11355, you'll see this:
```
<gridsize name="1 mm" value="2.834"/>
<gridsize name="2 mm" value="5.669"/>
```
Ipe does not support non-integer grid sizes since 2004.   If you remove the two lines, it will work.

Is your file very old? The problem is actually in your style sheet, so you need to fix it there and update all documents that use.

**Comment by mkraska** [comment]
Thank you, the method worked. Yet the file is approximately 5 years old and between 7.2.5 and 7.2.13 IPE must have lost the ability to handle files with non-supported style entries like the one you mention. 

I'd recommend to not just let the file opening crash but to ignore the non-supported entries and perhaps issue a warning about that.

**Comment by otfried** [comment]
Silently ignore non-integer grid size in 7.2.24.
