### ISSUE TITLE
OSX: Color choosing dialog

### ISSUE THREAD

**Issue by fulvioforni** [otfried/ipe#38]
Changing the color of an object works well if one use the menu with "written" colors (red, green, blue...)

Colors do not change if one click on the colored "square" on the left of the menu: 
- after click, a new window appears
- click on the desired wheel of colors
- close the window
- the color of the selected object is unchanged.

Thank you,
Fulvio

**Comment by otfried** [comment]
It works a bit different from before, because the OSX color dialog isn't modal:

Click on the color button, the OSX color dialog will appear.  Choose your color in the color dialog.

Now, press the color button again, and it will be applied to your objects.   As long as you don't close the color dialog, you can select new colors in the color dialog and apply them to objects in Ipe using the color buttons.

**Comment by fulvioforni** [comment]
Very good. It works. Tricky to guess by myself.

It is nice to have an extended palette of colors available.

(note that the "square" near the menu does not change color, a very minor
thing).

Thank you,
Fulvio

**Comment by otfried** [comment]
Actually, the square button indicates the "current color".  This is the color that will be given to newly created objects.   Choosing an absolute color with the color wheel does **not** change the current color - it only updates the color of the selected objects.  So the behaviour is correct.

**Comment by Zacharias030** [comment]
So as a follow up:
How do I set the color of newly created objects to this lovely custom shade of green that I am fond of today?

I can't find a way to make the color "stick".

**Comment by otfried** [comment]
As I said, choosing an absolute colour with the colour wheel does not change the current color.   Many years ago, the decision was made that absolute attributes can never be the current attributes, to encourage users to learn how to put their favourite attribute values in a style sheet, which makes them easy to use again.

This having said, there is a trick:  After changing the colour of some object using the absolute colour button, right-click on the object and say "Pick properties".   Newly created objects will then have the same colour.

Perhaps it's time to revisit this and allow absolute attribute values in the UI settings directly.

**Comment by Zacharias030** [comment]
My perspective is that of someone brand new to IPE, but I got a few-hour introduction from an experienced user whom I could teach the applying-color "trick" from above:

>"Click on the color button, the OSX color dialog will appear. Choose your color in the color dialog. Now, press the color button again

With fresh eyes it is not clear to me, why the collection of colors that I can 'save by dragging' in the color picker's little colored boxes would not somehow be linked to the collection of colors that I can pick from the 'official list' (that is apparently populated by style sheets).

That being said, let me send my high regards for the creation of this spectacular program!

**Comment by Zacharias030** [comment]
Let me visualize what I mean:
<img width="635" alt="color_palette_ipe" src="https://user-images.githubusercontent.com/6465504/74083383-c4ab4d80-4a63-11ea-878c-9591f4f79acc.png">

I understand from reading the manual that I am somehow using the program all wrong and I should use a stylesheet with symbolic attributes instead. What I haven't figured out yet is if IPE can help me 'exporting properties' like the nice colors I picked into a stylesheet (which I guess would resolve my confusion with the two color collections as well).

**Comment by otfried** [comment]
The behaviour of the OSX color dialog is not ideal - but it's caused by the fact that I need to support three different UI kits (Windows, Linux, OSX), and I need to keep the layer in between simple.

I'll look at it again if I can improve it, but I think my previous testing showed that updating all selected objects whenever the user drags the cursor in the colour dialog doesn't lead to a good experience.

As for letting Ipe help you make a style sheet:  Currently, the best you can do is use the color dialog to select an absolute color for one of your objects.  Then right click the object and select "Edit XML" so you can copy and paste the color value.

I keep my personal style sheet open in a separate editor.  Whenever I have updated it, I press Ctrl+Shift+U in Ipe to reload the style sheet.

**Comment by otfried** [comment]
But it's a good idea to add a new function that allows you to simply add a new colour to your style sheet.

**Comment by Zacharias030** [comment]
Really good advice! Thank you.

**Comment by otfried** [comment]
I've changed how absolute attributes are treated in the UI in 7.2.15.

There is a new section in the manual to help users make their first stylesheet, and a new information message when they open the color chooser on OSX.
