### ISSUE TITLE
files created in older versions 

### ISSUE THREAD

**Issue by ferdechi** [otfried/ipe#388]
Hi: I have a bunch of IPE files I created in older versions of IPE, and turns out I cant open/edit any of them in the newest version of IPE. Why are you guys restricting this? Seems all the work I have done for the last few years is completely useless now.  And I cant find older versions of the IPE software either. So I am very much stuck. Any suggestions?

**Comment by otfried** [comment]
Ipe can still process all files created since Ipe 2.0 released in 1993.

However, to keep the Ipe library maintainable, the core library only reads files made with Ipe 7.   If you have files made with Ipe 6, you'll need to convert them using ipe6upgrade (possibly after running ipeextract): https://ipe.otfried.org/manual/manual_68.html

If you have even older files made with Ipe 5 or earlier (that is, from the last millenium), you'll need to use ipe5toxml (the link is on the Ipe homepage).

If you have files where this doesn't work, that would be a bug - attach them here and I'll fix the problem.

**Comment by ferdechi** [comment]
Thanks so much, this does the job. Sounds you have to do it manually file per file from the cmd, correct?

**Comment by otfried** [comment]
I would write a loop in the shell, or a small script to convert a bunch of files.

**Comment by ferdechi** [comment]
Thanks again - I havent done low level coding for a while and have become quite rusty on it. The way I am doing is just by copying the the files (say figure1.eps) into the bin folder where the ipeextract.exe file is and then execute from the CMD ipeextract figure1.eps. That creates figure1.xml and seems to solve my problem, as I can then open that figure1.xml using IPE. I had the hope that I could copy a bunch of files in there and do ipeextract *.eps so it would convert all the eps files into xml files, but that didnt work. In case you have an example  on how to do that "loop in the shell" I would appreciate it if you can share it. If not, no big deal. It takes a little extra time but I can still convert the files. Thanks so much for your help again. Regards from Denver, CO. Fernando

**Comment by otfried** [comment]
On Linux or MacOS, it would be as easy as writing
```
for f in *.eps; do ipeextract $f; done
```
I don't use Windows myself, but googling seems to suggest it should look like this:
```
for %f in (*.eps) do ipeextract %f
```

**Comment by ferdechi** [comment]
Thanks - that worked perfectly!
