### ISSUE TITLE
How to set ipe as my default program for ipe files on Ubuntu 20.04 with x86_64?

### ISSUE THREAD

**Issue by pengdlzn** [otfried/ipe#395]
I have installed ipe 7.2.24-1 on my Ubuntu 20.04 with x86_64, and I have drawn some figures by ipe.

I would like to set ipe as my default program for ipe files. I right clicked an ipe file, and then I wanted to find ipe after clicking "Open With Other Application". However, I cannot find ipe in the lists of recommended application, related applications, or other applications.

My final goal is to open an ipe file by ipe application when programming in Python by calling "subprocess.call(('xdg-open', "myfile.ipe"))". In Python programming, I have managed to create an ipe file, where the file contains some points as output. Now I want to open it with ipe application immediately so that I can see the points in the ipe application, which requires that the default program for an ipe file is the ipe application.

**Comment by otfried** [comment]
How this works varies between different Linux distributions.  

On my Linux Mint system (based on Ubuntu), I can choose Open With -> Other application, and then simply type "ipe" :

![image](https://user-images.githubusercontent.com/9983417/122200364-43f03300-ce9b-11eb-9a3c-be9b6f6ffa89.png)

If Ubuntu does not have this option, you can perhaps find the Ipe executable from the file system?  Otherwise, you may have to add a `ipe.desktop` file to make Ipe show up in the list.   Here is one you could try:

https://salsa.debian.org/science-team/ipe/-/blob/master/debian/ipe.desktop

**Comment by otfried** [comment]
By the way, why don't you simply open the file in Ipe using
```
subprocess.call(('ipe', "myfile.ipe"))
```
?

**Comment by pengdlzn** [comment]
> How this works varies between different Linux distributions.
> 
> On my Linux Mint system (based on Ubuntu), I can choose Open With -> Other application, and then simply type "ipe" :

That method does not work for my case (see my screenshot below).
![Screenshot from 2021-06-17 10-28-12](https://user-images.githubusercontent.com/12211925/122321700-d86b9b80-cf56-11eb-880a-454d27fa7c6b.png)


> If Ubuntu does not have this option, you can perhaps find the Ipe executable from the file system? Otherwise, you may have to add a `ipe.desktop` file to make Ipe show up in the list. Here is one you could try:
> 
> https://salsa.debian.org/science-team/ipe/-/blob/master/debian/ipe.desktop

I have added 'ipe.desktop' into folder /usr/share/applications, but Ipe does not show up in the list.

**Comment by pengdlzn** [comment]
> By the way, why don't you simply open the file in Ipe using
> 
> ```
> subprocess.call(('ipe', "myfile.ipe"))
> ```
> 
> ?

Fortunately, subprocess.call(('ipe', "myfile.ipe")) works!
Thanks a lot, Otfried!
