### ISSUE TITLE
Feature Request : Add engine selection option in user defined stylesheet.

### ISSUE THREAD

**Issue by liubenyuan** [otfried/ipe#40]
Some `.isy` are pdflatex based while some new ones are xelatex based, so it would be great if I could set the latex engine in `.isy`, or select a default latex engine in `ipe.conf`

**Comment by otfried** [comment]
prefs.tex_engine will set the tex engine for newly created documents.  Once created, the setting is part of the document.

I thought about letting the style sheet set it, but usually there are other changes you need to make (e.g. install fonts on your computer, provide style files, disable auto-latex because xetex is much slower, etc.)
