### ISSUE TITLE
Cannot open a file

### ISSUE THREAD

**Issue by rjd23** [otfried/ipe#418]
I've tried ipeextract and ipetoipe to recover. I have also checked creator and producer of the pdf is Ipe. Executing 7.23 on Windows, also tried 7.24. The file was synced using GoogleDrive. 
Thanks for this very nice piece of software!
[Grafiques.pdf](https://github.com/otfried/ipe-issues/files/8157733/Grafiques.pdf)
.

**Comment by otfried** [comment]
Here is a fixed copy of the file:

[Grafiques.pdf](https://github.com/otfried/ipe-issues/files/8159924/Grafiques.pdf)

The problem was that you have a layer whose name contains a space.  I've replaced "_TikZ replaced" by "_TikZ_replaced" to fix this.

I'll need to look why Ipe did not stop you from making this change.  The file format uses a space as the separator between layer names in the view elements, so layer names cannot contain spaces.

**Comment by rjd23** [comment]
Thank you very much for the fast and efficient answer! The layer was created by an ipelet called ipe2tikz https://github.com/QBobWatson/ipe2tikz . Maybe that is useful.
Big fan of your work on Ipe and in research.
Greetings,
Rafel
