### ISSUE TITLE
Make view selector a consistent width.

### ISSUE THREAD

**Issue by jan-ferdinand** [otfried/ipe#421]
When going through the various views of an animated figure, the UI object highlighted in the picture below changes it's width since the numbers “1”, “2”, “3”, and so on do not have the same width. Because of that, the entire sidebar changes it's width, causing the figure to slightly jiggle around from one view to another.

![image](https://user-images.githubusercontent.com/4719768/159897883-9806a80b-d0ee-4328-8de4-94d9dc55b901.png)

If the view selector (and probably the page selector) had a constant width, the figure would be nicely static.

Of course, this is only very slight inconvenience. It feels like the fix could be simple – or unproportionally hard. 😬

**Comment by otfried** [comment]
Is this on Windows or Linux?  And which Ipe version?  The screenshot looks like Qt on Linux, but I cannot reproduce the problem there.

One thing you can do to avoid this is to change `prefs.view_button_prefix` and `prefs.page_button_prefix` to make them shorter (see the examples in `prefs.lua`).

**Comment by jan-ferdinand** [comment]
Ah, sorry for not including system info. Your guess is on the mark – Linux with Qt. The version of ipe is 7.2.23, which I guess is not even up to date. (What is my package manager doing? 🤔)

The described method does indeed stop the view button from jerking the main drawing area around. Thank you!

I'm closing this issue because it is solved for me. Should you want to investigate why the behavior is different between our respective ipe instances, I'm happy to assist in nailing this down. In that case, feel free to re-open the issue. However, I can also very well imagine that there are more exciting things to do in life. Or that a more up-to-date version of ipe doesn't have this behavior.

**Comment by mglisse** [comment]
> Is this on Windows or Linux? And which Ipe version? The screenshot looks like Qt on Linux, but I cannot reproduce the problem there.

I am seeing the same thing on Linux (Debian testing) with Ipe 7.2.25 and Qt 5.15.4 (just to confirm that it isn't restricted to one user).
[Screencast from 07-22-2022 03:13:24 PM.webm](https://user-images.githubusercontent.com/10097863/180447529-ba5e76e5-da19-4ea3-b15a-3f3c137f3e79.webm)

**Comment by otfried** [comment]
![image](https://user-images.githubusercontent.com/9983417/182655010-8995ccb3-589a-442c-8f32-f2ec00cba6e9.png)

Your's looks completely different from the way it looks for me - also the space between the checkbox and the button is missing.

Do you have some stylesheet for Qt, by any chance?   Are you perhaps running KDE?

**Comment by otfried** [comment]
Could you try running with a Qt-style argument and see if it behaves differently?  E.g. start from the command line like this:
```
ipe -style gtk2
```

**Comment by mglisse** [comment]
I don't have gtk2. It looks like it is using Fusion by default. With other styles like Adwaita or Breeze, it looks a bit better, in particular I get some space on the right of the checkbox (much more than on the left).
![image](https://user-images.githubusercontent.com/10097863/182662025-e83b5661-10c2-471e-aba1-3d90c3e0ca6d.png)
The size of the sidebar still changes when I move between views/pages though.
I run gnome. I don't think I have done anything special to qt, but the exact list of packages the system installs could include surprises...
(By the way, I have 7.2.26 now, but it doesn't seem to matter for this.)

**Comment by otfried** [comment]
Interesting - I don't have either `Adwaita` or `Breeze`:
```
$ ipe -style help
qt5ct: using qt5ct plugin
QApplication: invalid style override passed, ignoring it.
    Available styles: cleanlooks, gtk2, cde, motif, plastique, qt5ct-style, Windows, Fusion
```
But it doesn't seem to matter - no matter which style I choose, the buttons do not change width.

Wait a second - could it be that my UI uses a font where all digits have the same width?

![image](https://user-images.githubusercontent.com/9983417/182790013-6dee56f3-d36a-4bee-b44e-c5d46f8912c9.png)

Do you have `qt5ct`?  What does it show in the Fonts tab?

**Comment by mglisse** [comment]
The styles I have available are
> Available styles: HighContrastInverse, HighContrast, Adwaita-HighContrastInverse, Adwaita-HighContrast, Adwaita-Dark, Adwaita, Breeze, qt5ct-style, Oxygen, Windows, Fusion

(some are provided by the packages kde-style-oxygen-qt5, kde-style-breeze and adwaita-qt)

qt5ct shows "Cantarell 11" for both General and Fixed width. That's a strange default, since Cantarell doesn't appear to have a fixed width... Gnome uses "monospace regular 11" so Qt did not get that choice from gnome.
(qt5ct also complains "the application is not configured correctly" and "The QT_QPA_PLATFORMTHEME environment variable is not set (required value: qt5ct).")
I changed the second font to Monospace 11 in qt5ct, set QT_QPA_PLATFORMTHEME=qt5ct, started ipe with `-style qt5ct-style`, but I am not seeing any difference :disappointed:

**Comment by otfried** [comment]
Very nice, we have found the problem.

Traditionally, many fonts use digits that are exactly the same width (even if the font is not itself monospaced), simply because you want number to line up correctly when you create a table with numbers. (https://en.wikipedia.org/wiki/Typeface#Typesetting_numbers).

This is what keeps the View/Page buttons on my Ipe UI exactly the same width.  It took me a while to go through the fonts on my system until I found one that actually has digits with differing width (the one I finally found is `UnBatang`, a Korean font...)

Apparently Cantarell 11 also has differing widths for the digits.  The reason you cannot see a change when you switch the "Fixed width" font in `qt5ct` is because the Ipe UI (like other UIs) does not use the fixed width font - you would have to change the "General" font to see a change in behaviour.

I'm not sure what the right solution to the issue is.   I have tried making the button font monospaced, but that looked really bad.  Note that you can always change the `prefs.view_button_prefix` as explained above.

**Comment by mglisse** [comment]
> Very nice, we have found the problem.

Indeed, changing the main font to Ubuntu stops the size changes (in case I forget and read this again: need to set QT_QPA_PLATFORMTHEME in the environment).

> I'm not sure what the right solution to the issue is. I have tried making the button font monospaced, but that looked really bad. 

I guess it should be possible to look at the maximum of the sizes of the 10 digits and force a minimum width based on that, but that feels a bit like a hack. Or is there something standard like `em` that can be used here?

Thank you for the investigation, I think I'll simply use the Ubuntu font with ipe for now.

**Comment by otfried** [comment]
I've experimented a bit with using
```
    QFontMetrics fm(iViewNumber->font());
    int w = fm.horizontalAdvance(QIpe(vno));
```
and then setting `setMinimumSize` based on that, but it's not easy to get this to work as we don't know how big the button is without the text.  I can look at this again when I have some more time, but it doesn't seem to be an urgent issue.

**Comment by mglisse** [comment]
> it doesn't seem to be an urgent issue

Indeed, it is really not a priority, it doesn't affect that many people, several easy workarounds are explained in this PR, and the "bad" behavior is not that much of a problem.
