### ISSUE TITLE
Transparent bounding box

### ISSUE THREAD

**Issue by brunolnetto** [otfried/ipe#436]
Hi,

I have an image that I would like to surround by a transparent bounding box. After box creation, I can omit the inner color content by selecting the option "Stroke & Fill > stroke only". However, it keeps still the contour color.  How to proceed from here?

**Comment by Willem3141** [comment]
You can add your bounding box to a layer named `BBOX` and hide the layer. See also [§8.2.5 of the manual](https://ipe.otfried.org/manual/manual_views.html).

**Comment by brunolnetto** [comment]
I cannot reproduce your explanation. The minimal example I can imagine is: 

1. Draw a circle;
2. Draw a rectangle around it;
3. Hide the rectangle SOMEHOW, but not as a layer or view;
4. Export the image;

Now, the image bounding box is defined by the rectangle, and not by the circle.

**Comment by otfried** [comment]
What exactly are you trying to achieve?  You want a PDF image that is larger than the circle you have drawn?

There are many ways to achieve this, the easiest being the one Willem mentioned.  I'm attaching an image like that here:

[circleinbox.pdf](https://github.com/otfried/ipe-issues/files/9638378/circleinbox.pdf)

Alternatively, you could define a new layout, where you set the paper size to the exact figure size you want and where you set `crop` to `no`, so that the output figure will have exactly the size you want.

Finally, you could define an opacity value `transparent` (with an opacity value of zero), and use that for the surrounding box.  The difference is that this would actually write the box to the PDF file, it would just now show up in the PDF viewer.

For the second and third method you need to create a style sheet, that's why the first one is the easiest.

**Comment by brunolnetto** [comment]
Option 2 requires to obtain figure size. I can comprehend option 3. I even think we had this conversation in the past, but I am getting old to remember.
