### ISSUE TITLE
Small error in https://github.com/otfried/ipe-wiki/wiki/Presentations#printing-notes

### ISSUE THREAD

**Issue by guenterrote** [otfried/ipe#453]
If two views show the same set of layers, they are both deleted (even if maximal).

Possible fix:

REPLACE
     if j~=i and subset(vis[i], vis[j]) then
BY
     if j~=i and subset(vis[i], vis[j]) and (i>j or not  subset(vis[j], vis[i])) then

(This supposedly keeps the first view of a set of equal views.)

**Comment by guenterrote** [comment]
ANOTHER MATTER:

> the script needs to be saved as "ipeweed.lua" in (e.g.) ~/.ipe/scripts, and the first five lines need to be replaced by
```
local inname = argv[1]
local outname = argv[2]
```

CAN lua DETECT ITSELF HOW IT WAS CALLED AND DECIDE TO GET THE ARGUMENTS IN AN APPROPRIATE WAY?

**Comment by otfried** [comment]
Sure: the `argv` variable is provided by `ipescript`, while the Lua interpreter provides `arg`, so you could write
```
if argv then arg = argv end
inname = arg[1]
outname = arg[2]
```
And obviously I can simply add the `arg` name to ipescript so that the same code would work...

I would actually prefer if the authors of such scripts provide them as ipescripts, because those are much easier to use for normal mortals.   Setting everything up so that the Lua interpreter on your system can find `libipelua.so` when you say `require "ipe"` is non-trivial, that's why I made ipescript in the first place.

**Comment by otfried** [comment]
The page

https://github.com/otfried/ipe-wiki/wiki/Presentations#printing-notes

is a wiki - you can simply edit it yourself.

**Comment by guenterrote** [comment]
Made my fix. (Hesitated to make the other change; should one remove "require ipe" in that case?)

**Comment by otfried** [comment]
I'll do it.
