### ISSUE TITLE
Flatpak

### ISSUE THREAD

**Issue by hmenke** [otfried/ipe#458]
I have packaged Ipe for Flatpak: https://github.com/hmenke/org.otfried.Ipe

Are you interested in publishing this on Flathub?

**Comment by otfried** [comment]
Nice that it's now possible to reuse an existing Latex installation - when I looked at snapcraft and flatpak last, this wasn't possible and made packaging Ipe pointless...

If you take care of maintaining it, then feel free to publish it on Flathub.

**Comment by otfried** [comment]
Thanks for doing this!

I've finally tried out the Ipe flatpak today, and added a link from the Ipe webpage. 

Some questions:
1. Why do you compile `enchant` - what is it used for?
2. Why the dependency on `org.kde.Platform`?   When you first install Ipe, it's presented as a very heavy dependency (> 300MB compared to the 3MB Ipe) - ultimately only some smaller part is installed - is that how you get Qt6?

We should find a way to provide instructions for users who want to reuse their distribution's texlive, rather than reinstalling it through flatpak.

Currently, the spell checking doesn't work.   Ubuntu doesn't seem to have a qtspell package for Qt6, so I made the default to disable spell checking - you would have to reenable it.  In the next release I'll change the variable from `IPE_NO_SPELLCHECK` to `IPE_SPELLCHECK` so you can simply add that to the make command.

**Comment by hmenke** [comment]
> 1. Why do you compile `enchant` - what is it used for?

That is a dependency of QtSpell: https://github.com/manisandro/qtspell/blob/1b6897fe0d83b47492b0a7ed4ab9e7494df7e96f/CMakeLists.txt#L29-L40

> 2. Why the dependency on `org.kde.Platform`?   When you first install Ipe, it's presented as a very heavy dependency (> 300MB compared to the 3MB Ipe) - ultimately only some smaller part is installed - is that how you get Qt6?

Yes, unfortunately that is how Qt applications are built in Flatpak: https://docs.flatpak.org/en/latest/qt.html
However, this runtime is shared with all the other applications that are using Qt6 as well.

> We should find a way to provide instructions for users who want to reuse their distribution's texlive, rather than reinstalling it through flatpak.

That is a bit tricky. You saw the instructions to use an existing TeX Live that I added to the README. However, that is limited to an installation obtained from https://tug.org/texlive/ because these upstream binaries are statically linked to everything except glibc, so they work pretty much anywhere. This is quite different from distribution packages which link dynamically to the distribution-provided libraries like ICU, libpng, etc. Finally there is also no way to remap paths when bind-mounting something into the Flatpak sandbox, so a TeX Live installation in `/usr/bin` on the host cannot be used because `/usr/bin` already exists in the sandbox.

> Currently, the spell checking doesn't work. Ubuntu doesn't seem to have a qtspell package for Qt6, so I made the default to disable spell checking - you would have to reenable it. In the next release I'll change the variable from `IPE_NO_SPELLCHECK` to `IPE_SPELLCHECK` so you can simply add that to the make command.

I see. To be honest I didn't test spell-checking at all, because I don't really use it. Does it not work in the Flatpak version as well or only on Ubuntu? If it doesn't work in the Flatpak I will have to investigate why.

**Comment by otfried** [comment]
The fact that it's not possible to reuse the distribution's TeX installation is what has kept me from exploring snapcraft and flatpak in the past.  It just makes it so much less attractive to install Ipe that way if you have to reinstall TeX as well.

As for spell checking:  I had actually thought that QtSpell didn't support Qt6 yet (the webpage only mentions Qt4  vs. Qt5, and there is no Ubuntu or Debian package for it), so I'm now unconditionally setting `IPE_NO_SPELLCHECK` - so the support for spell checking is simply not compiled into the latest flatpak.

You would either have to comment out line 15 in `ipeui/Makefile`, or wait a few days for the next release, where I'll add `IPE_SPELLCHECK` to enable it on demand.

I should file a request to build a Debian/Ubuntu package for this - if I knew where...

**Comment by pglira** [comment]
For those stumbling upon this issue: to use IPE as a flatpak **without online latex compilation** one needs currently to:
```
flatpak install flathub org.otfried.Ipe
flatpak install org.freedesktop.Sdk.Extension.texlive
# there are different versions, I've selected version 22.08
# it's huge, 5.4 GB
```
Also: permissions/settings of the ipe installation can be simply modified using flatseal, e.g. for accessing files outside $HOME:
```
flatpak install flathub com.github.tchx84.Flatseal
```

PS: As stated by @hmenke above, extending the path with ``/usr/bin`` using flatseal in order to use the latex binaries on my host didn't work.

**Comment by CsatiZoltan** [comment]
Thanks for your comment @pglira. 

@hmenke If my TeX Live is installed to /media/... (a directory where I have write permission), can I configure flatpak to search that directory and therefore the flatpak version of Ipe recognizes my TeX Live installation? I ask it, hoping that the issue is only with /usr/bin, mentioned by you above.
