### ISSUE TITLE
Will not launch when accented characters are in the path

### ISSUE THREAD

**Issue by Gallion** [otfried/ipe#467]
On windows, Ipe will not launch if accented characters are in the path. For example, Ipe was under this path "C:\Users\MiniPC\Documents\Ecole\ipe-7.2.27\bin" and nothing would happen when double-clicking it. Changing "École" to "Ecole" fixed the issue.

**Comment by otfried** [comment]
What operating system are you using exactly?  Windows 10?   The file system is formatted with NTFS?

**Comment by Gallion** [comment]
Yes to both! More precisely, this is on Windows 10 LTSC 21H2.

**Comment by otfried** [comment]
I thought this is a regression, but on closer look it turns out this must always have been the case.   Unlike the fully Unicode-aware filesystem access functions in Ipe itself, Lua simply uses `fopen` to open Lua files - it cannot understand the UTF-8-encoded filenames that Ipe uses.

I could try to convert the path to the "code page" of the Windows system, but that would also break when the path uses characters that cannot be represented in this code page.   Perhaps it would be better if Ipe simple warned the user when the path is not clean ASCII.
