### ISSUE TITLE
Combo box "optimization" on Ipe 7.2.2 on Mac OS X

### ISSUE THREAD

**Issue by darrenstrash** [otfried/ipe#47]
There has been a recent change in behavior with the combo boxes under Mac OS X: if I reselect the currently selected item (e.g., "heavier" for line width), then no action is executed. In other programs, this isn't a problem...but it is problematic in Ipe. Here's why:

Historically, when you select an item in Ipe, its properties do not show up in the left-hand toolbox; instead it shows the properties of the last item you edited. Unfortunately, with the new optimization, this means that I may have to click twice to get the property I want: first click a property I don't want, then click the property I do want. Here's an example to illustrate:

1.) Make line segment #1.
2.) Make line segment #2.  Decide to give it a "heavier" line width.
2.) Re-select line segment #1.
3.) Now, if I want to make it "heavier", I need to first select a different line width, then select "heavier." This is because the property still is listed as "heavier" even though line segment #1 is not _really_ heavier. Therefore, if I select heavier, no action is executed.
## System Specs: 

Mac OS X 10.11.2 (15C50)
Ipe 7.2.2, prebuilt binary for Mac OS X

**Comment by otfried** [comment]
Unfortunately it doesn't seem as if I can fix this easily.  The combo box control in Cocoa simply doesn't send a notification when the user selects the currently selected item, and I don't know how to achieve this without essentially reimplementing the combo box.

I believe many people use the right-click object menu to change attributes of an object (or a collection of objects).

**Comment by darrenstrash** [comment]
Thanks, Otfried. What do you see as a long-term solution? I can think of the the following solutions, which I would be happy to look into:

1.) Overriding the combo box behavior to emit the signal anyway. -> keep previous behavior
2.) Loading the properties of an object when selecting a new object. -> new behavior, potentially problematic as it changes workflows, such as using the last object's settings when creating a new object.

**Comment by otfried** [comment]
I looked at (1) briefly today - it doesn't seem easy to me.  The easiest solution might be to replace the NSComboBox entirely by a button with a popup menu.  That would have the added advantage that we can bring back the color squares in the color selectors.

(2) would have to be discussed on the ipe-discuss mailing list in quite some detail, as it would change the workflow a lot.  It would make it quite easy to accidentally use settings one didn't intend to use.

I'm not sure how much people consider this to be a problem anyway, as many people seem to change the properties of an object through its properties menu (the right-click menu).

**Comment by darrenstrash** [comment]
Thanks again for your response. I like your first thought...replacing the NSComboBox. Having the color squares back would be a very welcome bonus.

I have some experience in UI in other languages (including making custom elements). Please let me know if you would like to me to investigate.

**Comment by nathaniel** [comment]
Darren and Otfried, thanks for raising this and considering options.

Even before the Cocoa-based version of Ipe, I've been conflicted about the behavior of the properties pane in Ipe.  It can be used to
(a) control the attributes of the currently-selected objects, and
(b) control the attributes that will be assigned to newly-created objects.

I agree that the new behavior in Cocoa does make it less convenient for (a).  I like Darren's option (1), using a  popup menu; I have been missing the color boxes anyway!  (just what color is _seagreen_ anyway -- hard to guess without seeing it!)

But I have long considered that (2) is a useful approach, regardless of this new Cocoa issue.  What about adding checkbox in the properties panel, that determines whether or not the currently-selected object's properties are loaded in the panel?  This would make it more natural to use the panel to control the selection's properties, in addition to establishing a quick way to set the properties for new objects to match those of an exisiting object.

A second checkbox that would be handy--at the risk of overcomplicating the interface--would be one that allows the properties panel to be used as a _format painter_ -- something like "apply properties to object upon selection".  This couldn't be set together with "load properties of object upon selection", since the two behaviors would conflict.

Again, these two options have been on my mind as possible improvements for the properties panel for the past year, independent of the changes in 7.2.2 for Mac.  If you like, I can submit them as feature requests separate from this particular issue raised by Darren.

**Comment by otfried** [comment]
Problem solved - the trick is to use NSPopUpButton rather than NSComboBox.

It's strange that Cocoa has two so similar controls, but the documentation of neither control refers to the other one.

Here is a snapshot of the new version:
https://dl.dropboxusercontent.com/u/1840678/ipe-snapshot-0616.dmg

**Comment by nathaniel** [comment]
According to pages like this
https://www.raywenderlich.com/27388/core-controls-in-mac-os-x-part-12
The NSComboBox is aimed toward pull-down options _plus free user input_.
