### ISSUE TITLE
Ordering of symbolic attributes in UI

### ISSUE THREAD

**Issue by AndrewMartchenko** [otfried/ipe#65]
Hi

I created a custom color.isy file with color names such as red1, red2, ..., red9, and so forth for other common colors. The colors all work but do not appear in alphabetical order or the order in which they are defined in the isy file. It would be much more convenient (in my case) for all the shades of a particular color class to appear together.

My zipped style file is attached.

Thanks.
[mycolors.isy.zip](https://github.com/otfried/ipe-issues/files/230019/mycolors.isy.zip)

**Comment by otfried** [comment]
Why did you close this? It's actually on my list of things to improve.

**Comment by AndrewMartchenko** [comment]
Hi Otfried,

I closed this issue because on the following morning (after opening this 
issue) I edited a diagram and noticed that the problem was gone - the 
colors now appear in the same order as they are listed in my style file. 
Also, I could not reproduce the original problem on another computer so 
I decided to closed the issue.

By the way, I love love love the program. I've almost got everyone in 
the Engineering Department at La Trobe University (Australia) using it.

Regards,

Andrew Martchenko.

**Comment by joklawitter** [comment]
Hi @otfried, the problem that the color order in the stylesheet is not exactly reflected in the UI drop down menu stil exists - at least for me.  In particular, for the attached [color-order-test.zip](https://github.com/otfried/ipe-issues/files/5332464/color-order-test.zip) example, the order is mostly reflected except that under Win10 "red" is shifted after "black" and "white" and under Ubuntu also "gray" is moved up. There is no difference whether the style is loaded on startup via `prefs.styles` or afterwards via `Ctrl + Shift + S`. (With another style, I had the problem that exactly two colors got swapped, dark blue and dark gray.)

The change in order is also reflected in the saved file.

**Comment by otfried** [comment]
Well, I never did anything about this issue.  The order is determined purely by the internal code for the symbolic name, which is essentially assigned incrementally as names are encountered while Ipe is run.

It's also not clear what the right implementation is.   Some users would prefer the names to be alphabetically sorted, others want the order from the style sheet (which is not actually preserved by Ipe and is not well defined, because symbolic names can be defined in dozens of style sheets in the current cascade), and others asked for frequently used names to be put on the top.

The current plan is to move the least-recently used name to the top - if you have any comments on that, please leave them on ticket #241 .
