### ISSUE TITLE
\includegrafics{file.pdf} not working

### ISSUE THREAD

**Issue by emilio-condordrives** [otfried/ipe#73]
After including the graphicx package in the preamble, I was not able to include correctly the file.pdf, even with the file.pdf in the same folder than the ipe file. The error log is very big, but searching on it, I figured out this message:

! Package pdftex.def Error: File `file.pdf' not found.

Can anyone help me please!
thank you

pd.: Working on MAC OS X, IPE 7.2.2

**Comment by otfried** [comment]
Using \includegraphics to include an external PDF file into an Ipe document is not currently supported by Ipe (limited support is planned for later this year).

It should already work for some PDF files, but the included file will only be correctly shown in the PDF file produced by Ipe, _not on the Ipe display_.

When Ipe runs pdflatex, it runs it in a specific directory (shown as "Latex directory" under Ipe -> Help -> Settings).  If you copy the file.pdf there, it should be found.   Otherwise, use the \graphicspath command for the graphicsx package.

**Comment by emilio-condordrives** [comment]
Thanks for the answer !
