### ISSUE TITLE
Line opacity does not effect arrow head

### ISSUE THREAD

**Issue by AndrewMartchenko** [otfried/ipe#84]
As the title suggests, changing the opacity of a line does not change the opacity of the arrow head.

**Comment by otfried** [comment]
Ipe doesn't support **group transparency**.  Since arrows are simply symbols drawn using strokes and filled shapes, that means that if arrows could be transparent, you would see their internal makeup - and that is generally undesirable, as the following screen shot shows (made by enabling transparency in the arrow drawing code):

![screenshot from 2016-06-21 22 40 45](https://cloud.githubusercontent.com/assets/9983417/16245474/59df1356-3801-11e6-8870-7ccecf28e5df.png)

**Comment by otfried** [comment]
So allowing transparent arrow would require me to implement group transparency, which is not a high-priority feature (it also hasn't been requested otherwise).

**Comment by AndrewMartchenko** [comment]
Fair enough. Thanks for the example of the transparent arrow head, I used it in my drawing and it looks pretty good.
