### ISSUE TITLE
Provide binaries of older releases (cf. SourceForge ticket #29)

### ISSUE THREAD

**Issue by czietz** [otfried/ipe#9]
Since you've unfortunately decided in the SF ticket mentioned above not to support Windows versions previous to Windows 7 starting with Ipe 7.1.7, I suggest to at least provide older releases (such as 7.1.6) as binary. The download archive has gone away with your transition from SourceForge to GitHub.

PS: As I didn't expect an answer to my old ticket anymore, I long did as you suggested and patched Ipe 7.1.7 to run on older Windows versions again. However, other users might benefit from getting a precompiled version that works for them.
PPS: A "Quickstart for Windows" section in the source distribution's install.txt would have been most helpful.

**Comment by otfried** [comment]
Ipe 7.1.8 is available as a binary package for Vista and XP.   

I'll make this package available for important releases (e.g. when the Ipe file format has changed).

**Comment by czietz** [comment]
Thank you very much!

Instead of conditionally compling for Windows Vista and XP via a #define you could also dynamically load the "offending" function GetGestureInfo. This results in one binary package that will use gestures under Windows 7 and above but still runs under older versions. 

This is the patch I wrote to get Ipe 7.1.7 running for me, while retaining gesture functionality:
http://www.chzsoft.de/storage/ipe-vista-patch.diff

**Comment by otfried** [comment]
It would have been nice if you had attached this to your previous bug report.  Would have saved me time and given a better solution.    Sigh.

**Comment by czietz** [comment]
Well, after you closed the previous ticket with "wont-fix" stating it wasn't "worth [your] time", I didn't think you'd be interested in the solution.

However, it isn't hardly an ingenious patch I came up with. I merely implemented what I already had suggested to you in the previous bug report: loading the function dynamically.

**Comment by otfried** [comment]
When I marked the ticket "wont-fix" on July 5, you immediately said you had "long" done it yourself.  So my "wont-fix" decision does not explain why, when you made the patch and compiled it yourself, you didn't spend the few minutes to add the patch to the ticket.  I could easily have included it and made it available for others. 

Yes, my "wont-fix" decision was wrong - it was much easier than I thought.   I'm not a Windows developer, I don't even have Windows on my development computers.   I compile the Windows version with a cross-compiler under Linux, and I test using wine.  

I'm making Ipe freely available, even though I have very little time for development.  People who demand that I solve their problems, call my decisions *unfortunate*, and tell me what I should *at least* do are not very popular in the open-source community.

You say *other users might benefit from getting a precompiled version that works for them*, but when you built exactly such a version **never** thought about sharing it?

You say *A "Quickstart for Windows" section in the source distribution's install.txt would have been most helpful*, but when you figured it out, you **never** thought about writing it up and adding it to the Wiki?

For what it's worth, I only figured out how to compile on Windows because other Ipe users explained it to me.

I suggest you reconsider your attitude towards open-source software.

**Comment by czietz** [comment]
Enjoy: https://github.com/otfried/ipe-wiki/wiki/Downloading,-Compiling,-and-Installing-Ipe#windows-1

**Comment by otfried** [comment]
Very nice, thanks!

**Comment by otfried** [comment]
Your patch for dynamically loading GetGestureInfo will be in the next release.
